### ISSUE TITLE
Error when running example_rag.py

### ISSUE THREAD

**Issue by mferris77** [metamind-ai/autogen-agi#1]
Hi there - first congrats on putting this together, looks like a very promising project.  

I tried running example_rag with some of my own PDFs, and it seemed to run fine as far as ingesting the documents and sending the info to chatgpt - but an error occurred in whatever the next step is - specifically "OpenAIWrapper' object has no attribute 'extract_text_or_function_call':

```
DEBUG:openai._base_client:HTTP Request: POST https://api.openai.com/v1/chat/completions "200 OK"
ERROR:utils.rag_tools:Error in RAG fusion: 'OpenAIWrapper' object has no attribute 'extract_text_or_function_call'
Traceback (most recent call last):
  File "C:\DEV\AutoGenProjects\autogen-agi\example_rag.py", line 55, in <module>
    main()
  File "C:\DEV\AutoGenProjects\autogen-agi\example_rag.py", line 39, in main
    answer = get_informed_answer(
  File "C:\DEV\AutoGenProjects\autogen-agi\utils\rag_tools.py", line 536, in get_informed_answer
    nodes = get_retrieved_nodes(
  File "C:\DEV\AutoGenProjects\autogen-agi\utils\rag_tools.py", line 339, in get_retrieved_nodes
    query_variations = rag_fusion(query_str, query_context)
  File "C:\DEV\AutoGenProjects\autogen-agi\utils\rag_tools.py", line 288, in rag_fusion
    rag_fusion_response = light_gpt4_wrapper_autogen(
  File "C:\DEV\AutoGenProjects\autogen-agi\utils\misc.py", line 142, in light_gpt4_wrapper_autogen
    return light_gpt_wrapper_autogen(client, query, return_json, system_message)
  File "C:\DEV\AutoGenProjects\autogen-agi\utils\misc.py", line 128, in light_gpt_wrapper_autogen
    response = client.extract_text_or_function_call(response)
AttributeError: 'OpenAIWrapper' object has no attribute 'extract_text_or_function_call'
```

This could be my error as I noticed you were relying on autogen v0.2.0b4 - I actually installed v0.2.2, but there doesn't seem to be much difference in that function between 0.2.0b4 and 0.2.2.  My config json file has gpt-4-1106-preview and gpt-3.5-turbo in it.  I see in rag_tools you're defining LLM_CONFIGS and then referencing 'llm4' in the 'get_informed_answer' function.  

Is my use of 0.2.2 possibly the issue or is it that I need to define an LLM config key/value pair named just 'gpt-4"?

**Comment by JKHeadley** [comment]
Thanks for pointing this out! I'll definitely check it out. My gut says it's an autogen version issue but if that's the case then I need to update the project.

I'll try to look at this soon and get back to you.

**Comment by JKHeadley** [comment]
@mferris77 should be fixed with https://github.com/metamind-ai/autogen-agi/pull/5
